### PR TITLE
SrtUri

### PR DESCRIPTION
**Pull request by robertream**
@russelltg

I've started on #144 though it is a work in progress still. There are a few more parameters left to implement, but I am pretty confident with the direction this is going. I haven't integrated the SrtUri with anything yet, so it wouldn't be a breaking change to merge this. This will be helpful in maintaining compatibility with the reference implementation CLI URI syntax. We can accommodate more than one key name per option, so it won't impede us from improving on the URI syntax while maintaining backwards compatibility.

### CODE REVIEW

**Comment by robertream** [comment]
@russelltg influenced by the URL model, I decided to improve on SocketAddress to include domain host names, I am even more confident this should be merged now

**Comment by russelltg** [comment]
Maybe I'm missing something but why do we want to include host names? ToSocketAddrs already can handle that, and the protocol doesn't care about hostnames (like TLS does).....what's the benefit?

**Comment by robertream** [comment]
> Maybe I'm missing something but why do we want to include host names? ToSocketAddrs already can handle that, and the protocol doesn't care about hostnames (like TLS does).....what's the benefit?

The advantage is that the full BindOptions enum can be built up and validated without having to actually resolve domain names, thus keeping the protocol library separate from the I/O libraries, but keep common data types for configuration for all integrations (e.g. tokio/std::net/GStreamer etc.). I envisioned the SRT URI being reused for configuration in multiple contexts, not just srt-transmit, and I was attempting to use the URI for configuration in another context, which motivated this.

**Comment by russelltg** [comment]
But the protocol library only cares about IP addresses, so isn't it both cleaner and more pure to keep domains away, and in IO land?

**Comment by robertream** [comment]
> But the protocol library only cares about IP addresses, so isn't it both cleaner and more pure to keep domains away, and in IO land?

The protocol also doesn't know about UDP socket buffer sizes, but it's still in the options structs. I had initially attempted to keep that purity by excluding these i/o concepts from the options model, but you also found it useful to add them back in. I don't think this is much different. Perhaps there's a better way to solve the UDP socket configuration problem differently as well, but for now, I'm ok with the impurity/complexity. It made implementation easier this way.

**Comment by russelltg** [comment]
I see, to natively support Uri's we need to have some sort of differentiation, I'm okay with it. I don't love it, and maybe longer term I'll find something I think is cleaner but for now it's fine.

**Pull request merged**
