### PR TITLE
Fix leaking vectors

### LINKED ISSUE #114: Buffer size is constantly growing while receiving packets (memory leak or... ?).
Hey everyone So i fired the [example](https://github.com/russelltg/srt-rs/blob/master/srt-tokio/examples/receiver.rs) for 1hour 15 minutes. And the problem is the internal vector is constantly growing (with some valgrind examples below) causing more and more memory usage over time.
I used the latest version of the repo - `srt-tokio = {git = "https://github.com/russelltg/srt-rs", branch = "master"}` . The way i received packets: 
1) Run  srt-live-transmit udp://:1234 srt://:4201 -v
2) Run ffmpeg -re -stream_loop -1 -i video.ts -c copy -f mpegts "udp://127.0.0.1:1234?pkt_size=1316"
3) valgrind --tool=massif ./my_proj (copy and paste of the example above) 
Results: 
First project (copy and paste from the [example](https://github.com/russelltg/srt-rs/blob/master/srt-tokio/examples/receiver.rs) ): 

Proj1
Proj1

Second project (there are some ffmpeg allocations involved but they work fine, don't mind them): 

Proj2
Proj2

So there are a couple of questions: 
1) Is such behavior expected ? If so when the `vec` will stop growing ? 
2) Is it useful to use `srt_socket.flush().await.unwrap();` to prevent such behavior ? 
Thanks in advance!

### PR DESCRIPTION
**Pull request by Lighty0410**
Not quite sure if the logic is 100% correct, but at least it works in my project. Faced no leaks with these changes after 1h15m stream so far. 
Probably gonna close #114  
Any suggestions are appreciated.

### CODE REVIEW

**Comment by russelltg** [comment]
The is not the solution I had in mind--but it's definitely a start. If you want to take a stab, the steps would look like:

1. Look at the reference implementation and see how they do it--is it fixed size, configurable, etc. I beleive it is configurable but I'm not totally sure. This would probably need to be exposed in `SrtSocketBuilder` and added to `ConnectionSettings`
2. Change these from `Vec`'s to `Deque`'s--the way you've currently implemented it it's `O(buffer size)` to reallocate, copy, and move into, when there is no real reason for this as Deques can do all these operations in constant time--and every time an element is added to these Deque's we'd need to pop one off if the buffer size max is hit.
3. Make sure there's no spots that are assuming that the full packet history is available, and that we don't need to change any of the logic surrounding these buffers

**Comment by Lighty0410** [comment]
> The is not the solution I had in mind--but it's definitely a start. If you want to take a stab, the steps would look like:
> 
>     1. Look at the reference implementation and see how they do it--is it fixed size, configurable, etc. I beleive it is configurable but I'm not totally sure. This would probably need to be exposed in `SrtSocketBuilder` and added to `ConnectionSettings`
> 
>     2. Change these from `Vec`'s to `Deque`'s--the way you've currently implemented it it's `O(buffer size)` to reallocate and copy, when there is no real reason for this as `Deque`s can do all these operations in constant time--and every time an element is added to these Deque's we'd need to pop one off if the buffer size max is hit.
> 
>     3. Make sure there's no spots that are assuming that the full packet history is available, and that we don't need to change any of the logic surrounding these buffers

Thank you a lot. Gonna explore these cases and push a commit when i'll have time (probably this/next week). Should i close the PR for now though ?

**Comment by russelltg** [comment]
You can just update this PR, no need to close it

**Comment by russelltg** [comment]
These should be all fixed now as of #117. Open an issue if that's not the case

**Pull request closed without merging**
