### PR TITLE
add test to repro high bandwidth freeze easily

### PR DESCRIPTION
**Pull request by russelltg**
I've added a deterministic test to repro #75

### CODE REVIEW

**Comment by russelltg** [comment]
(I'm looking at it, so no need for you to dig into it @robertream. I'll lyk if I need help)

**Comment by robertream** [comment]
> (I'm looking at it, so no need for you to dig into it @robertream. I'll lyk if I need help)

Nice, I love how side effect free state machine designs (or deterministic state transducer designs, to be more CS geeky) make stateful protocol code like this soooo easy to test. (state', input) -> (state'' output)

**Comment by robertream** [comment]
> > (I'm looking at it, so no need for you to dig into it @robertream. I'll lyk if I need help)
> 
> Nice, I love how side effect free state machine designs (or deterministic state transducer designs, to be more CS geeky) make stateful protocol code like this soooo easy to test. (state', input) -> (state'' output)

BTW, I am working on making a state machine similar to DuplexConnection for the MultiplexListener too. So we can run simulations between callers and a listener in faster than real time as well. :)

**Comment by russelltg** [comment]
Okay, figured out what's going on here--digging in the reference impl to see what they do:

The receive buffer size is not nearly large enough to deal with the latency*packet_rate product, so the receive buffer drops the packets, but the sender gets no notification of this--no NAK or ACK is sent for these packets. 

It seems like there are at least 3 issues going on here:
1. (the obvious one) buffer size is too small for this test
2. We don't retransmit on timeout (RTO in the spec)
3. We don't NAK packets that are dropped by the receive buffer--i'm not sure if this is proper of if you're just supposed to rely on RTO

**Comment by robertream** [comment]
> Okay, figured out what's going on here--digging in the reference impl to see what they do:
> 
> The receive buffer size is not nearly large enough to deal with the latency*packet_rate product, so the receive buffer drops the packets, but the sender gets no notification of this--no NAK or ACK is sent for these packets.
> 
> It seems like there are at least 3 issues going on here:
> 
> 1. (the obvious one) buffer size is too small for this test
> 2. We don't retransmit on timeout (RTO in the spec)
> 3. We don't NAK packets that are dropped by the receive buffer--i'm not sure if this is proper of if you're just supposed to rely on RTO

2) is why I added #119

3) a NAK would trigger a resend, the spec says we need to send a “false” ACK, to move the forward

**Comment by russelltg** [comment]
I think we do technically want a retransmit on full buffer--if the sender deems it's too late then so be it but retransmitting is fine.

I also assume we're supposed to use the reported buffer availability in the sender algorithm to make sure we don't overwhelm the buffer?

**Comment by robertream** [comment]
> I think we do technically want a retransmit on full buffer--if the sender deems it's too late then so be it but retransmitting is fine. We should likely just look at the reference implementation

Ok, that’s reasonable

> I also assume we're supposed to use the reported buffer availability in the sender algorithm to make sure we don't overwhelm the buffer?

I assume that’s why the reference implementation was stalling when we didn’t send a valid buffer length, though I don’t recall seeing this in any of the specs.

**Comment by russelltg** [comment]
Another interesting thing here--there is much more packet loss than I would expect--there's more packet loss than the connection even has, meaning we're not even beating normal UDP....yikes

**Comment by robertream** [comment]
> Another interesting thing here--there is much more packet loss than I would expect--there's more packet loss than the connection even has, meaning we're not even beating normal UDP....yikes
> 
> See if you agree with me--the math is at the end of the new test

I got high_bandwidth to work consistently by lowering the SND period to the extreme, I think the throughput problems are all timing related, the stall is a protocol/buffer problem.

**Comment by russelltg** [comment]
high_bandwidth (with increased buffer size, as in this branch) works at up to 90MB/s for me, which I think is pretty impressive

**Comment by robertream** [comment]
> Another interesting thing here--there is much more packet loss than I would expect--there's more packet loss than the connection even has, meaning we're not even beating normal UDP....yikes
> 
> See if you agree with me--the math is at the end of the new test



> high_bandwidth (with increased buffer size, as in this branch) works at up to 90MB/s for me, which I think is pretty impressive

yeah, nice!

**Pull request merged**
