### PR TITLE
Fix: use latest url crate

### PR DESCRIPTION
**Pull request by nipierre**
Closing #177.
Adding a regex to template ip from now unsupported host pattern for listener.

### CODE REVIEW

**Comment by robertream** [comment]
Sorry I didn't look at this sooner.
@russelltg why are all the tests failing? It looks like the've failing for a while?

**Comment by robertream** [comment]
https://xkcd.com/1171/

**Comment by russelltg** [comment]
if master gets merged into this then we'll at least get windows+macos+coverage

**Comment by russelltg** [comment]
I'd love to update this PR, and you've technically given me access, but I get an error:

```
remote: Resolving deltas: 100% (121/121), completed with 56 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access. Commits must have valid signatures.
To https://github.com/nipierre/srt-rs
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/nipierre/srt-rs'
```

I think it's because you opened this MR from your master branch which has protections. So I will have to wait for you to update the PR.

**Comment by russelltg** [comment]
just finished fixing up all the CI issues. Everything should pass once master is merged into here.

**Comment by nipierre** [comment]
Sorry, been hectic on my side lately, I'll do the rebase right away (@robertream or we use your cherry pick ;))

**Comment by russelltg** [comment]
This seems like a legit regression (repro'd locally, and main passes for me). I'll be happy to merge when you've fixed it

**Comment by nipierre** [comment]
Ok I see what's wrong, I'll try to fix it nicely.

**Comment by nipierre** [comment]
@russelltg Two things I crossed during the fix :
-  On my machine (MacBook Pro M1, latest macOS, srt w/ brew) the `stransmit_rs_ui::no_args` test is not passing for both branches but I guess it's ok.
`thread 'stransmit_rs_ui::no_args' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<error: The following required arguments were not provided:
>error: the following required arguments were not provided:
   <FROM>
   <TO>...
 
 Usage: srt-transmit <FROM> <TO>...
 
<For more information try '--help'
>For more information, try '--help'.

', srt-transmit/tests/stransmit_cmdline.rs:185:13`
- The `stransmit_rs_snd_rcv::basic_tcp` test fails and succeeds randomly for both branches.

**Pull request merged**
