### PR TITLE
Remove multiplex

### LINKED ISSUE #148: Multiplex server drops a client after a couple of seconds.
Hey everyone ! Since the recent repo updates, the multiplex server doesn't seem to be working. I tried to apply options and thought it was the case, but nope. All the same issues even when copy&pasting the `multiplex.rs` example. 
What's going on: whenever a client connects to the server, the client disconnects after a while (maybe around 5 seconds). 
For example (look at the timestamps) : 
```
[2021-12-14T14:30:38Z INFO  untitled3] SRT Multiplex Server is listening on port: 4444
[2021-12-14T14:30:42Z INFO  untitled3] New client connected: (ip_port: 127.0.0.1:58701, sockid: 10679579)
[2021-12-14T14:30:47Z INFO  untitled3] Send to client: (ip_port: 127.0.0.1:58701, sockid: 10679579) error: Custom { kind: NotConnected, error: SendError { kind: Disconnected } }
[2021-12-14T14:30:47Z INFO  untitled3] Client (ip_port: 127.0.0.1:58701, sockid: 10679579) disconnected
```
As you can see, after 5 seconds since the client has connected to the server the connection drops. It happens both for FFmpeg and a client application using this crate. 

Example: 
https://gist.github.com/Lighty0410/2b7b3f0695dd7f0b26b323f7a9f9db73 (slightly modified `multiplex.rs`, basically restreaming around 50mb/sec mpegts stream (in my case) )

Thanks in advance !

### PR DESCRIPTION
**Pull request by robertream**
This should fix #148
@Lighty0410 could you confirm?

### CODE REVIEW

**Comment by Lighty0410** [comment]
@robertream sadly, all the same 😢 . I tried to tinker with options, but no result whatsoever. 
https://gist.github.com/Lighty0410/9dcc19164e994d09cc9435a6a2b46a5f - multicast. 
https://gist.github.com/Lighty0410/1fbc4d567aeaf71521a27f6abd9a56d3 - receiver. 

The receiver drops after ~5 seconds.

**Comment by robertream** [comment]
> @robertream sadly, all the same cry . I tried to tinker with options, but no result whatsoever. https://gist.github.com/Lighty0410/9dcc19164e994d09cc9435a6a2b46a5f - multicast. https://gist.github.com/Lighty0410/1fbc4d567aeaf71521a27f6abd9a56d3 - receiver.
> 
> The receiver drops after ~5 seconds.

@Lighty0410 It's fixed now. I validated using your gists.

**Comment by Lighty0410** [comment]
> > @robertream sadly, all the same cry . I tried to tinker with options, but no result whatsoever. https://gist.github.com/Lighty0410/9dcc19164e994d09cc9435a6a2b46a5f - multicast. https://gist.github.com/Lighty0410/1fbc4d567aeaf71521a27f6abd9a56d3 - receiver.
> > The receiver drops after ~5 seconds.
> 
> @Lighty0410 It's fixed now. I validated using your gists.

Yeah, the example works now. Thank you ! I've tested a little bit further and here's another problem. When i try to restream the real mpegts stream, i get : [this](https://gist.github.com/Lighty0410/13c3aaae979d52a41a868b85683fa08c) . And the receiver drops even quicker than before (5-60 packets).
What's interesting. It seems like the listener doesn't drop the connection on its side since i neither see the message `info!("Client {} disconnected", client_desc);` in the end of the scope nor `info!("Send to client: {} error: {:?}", client_desc, e);` in the `send_all` future. 

How to reproduce: 

- srt-live-transmit udp://:1234 srt://:4201 -v (the original restream tool) 
- ffmpeg -re -stream_loop -1 -i output.ts -f mpegts "udp://127.0.0.1:1234?pkt_size=1316" (obtain the mpegts video somewhere. I guess even a single h264@720p stream + aac should be enough). 
- fire up the - [restreamer ](https://gist.github.com/Lighty0410/688ada3760fbc89d1abb45d8e5037ebe)
- fire up either the ffplay - ffplay srt://127.0.0.1:4444 or the [receiver ](uhttps://gist.github.com/Lighty0410/4c74498c446a969a6d1b4cd37faf85b7rl)

**Comment by robertream** [comment]
> Yeah, the example works now. Thank you ! I've tested a little bit further and here's another problem. When i try to restream the real mpegts stream, i get : [this](https://gist.github.com/Lighty0410/13c3aaae979d52a41a868b85683fa08c) on the listener side. And the receiver drops even quicker than before (5-60 packets). What's interesting. It seems like the listener doesn't drop the connection on its side since i neither see the message `info!("Client {} disconnected", client_desc);` in the end of the scope nor `info!("Send to client: {} error: {:?}", client_desc, e);` in the `send_all` future.

With the latest build I'm seeing your receiver code stall. The receive buffer was too small for the bit rate. I increased the buffer and it worked for over a minute, no problem.

**Comment by Lighty0410** [comment]
> 

Hmm, interesting. I increased the buffer size both for the sender and the receiver up to `8192 * 1000`. It doesn't stale anymore, indeed. However, as soon as the client connects to the listener, it receives around ~200 packets, and the listener panics with this message:
 
```
thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', /home/lighty/.cargo/git/checkouts/srt-rs-59753e5c7639345c/f680d83/srt-protocol/src/protocol/sender/buffer.rs:113:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Lighty0410** [comment]
@robertream awesome :). Now it works! Thank you a lot. Both ffplay and the receiver works. 
Is there anything worth testing/the way i can help further?

**Comment by robertream** [comment]
> @robertream awesome :). Now it works! Thank you a lot. Both ffplay and the receiver works. Is there anything worth testing/the way i can help further?

Great, thank you!

Any exploratory testing like this is helpful. Though it's close to working well, it's got plenty of rough edges. As far as I know, it has no use in any production scenarios, so maybe some of that: e.g. longevity, fluctuating latency, network congestion, packet loss, and any combination of these integrated with the reference implementation. Disregarding any dropped data, does the output pacing on the receiver closely resemble what the sender received through all these scenarios?

Also, maybe feedback on what missing capabilities/features are most compelling to you.

**Comment by Lighty0410** [comment]
> > @robertream awesome :). Now it works! Thank you a lot. Both ffplay and the receiver works. Is there anything worth testing/the way i can help further?
> 
> Great, thank you!
> 
> Any exploratory testing like this is helpful. Though it's close to working well, it's got plenty of rough edges. As far as I know, it has no use in any production scenarios, so maybe some of that: e.g. longevity, fluctuating latency, network congestion, packet loss, and any combination of these integrated with the reference implementation. Disregarding any dropped data, does the output pacing on the receiver closely resemble what the sender received through all these scenarios?
> 
> Also, maybe feedback on what missing capabilities/features are most compelling to you.

So far soo good! The latency is really low. For example.  . On the left side - the connection to the original srtlib implementation from the remote server. On the right - the restreamer from my local machine - the multiplex example I've sent previously. I connect to the remote listener with the original implementation and multiplex the connections to my local machine. Both of them played with low latency settings - `ffplay -fflags nobuffer -flags low_delay -framedrop` . 
In terms of longevity/packet drops, it also was good, i saw only ~3 packet drops in ~12 hours with the RTT of around ~50ms and peer latency of 1 second (before the sudden bandwidth spike).  I need to retest it for at a week with the new changes to provide feedback though.

The only issue i faced was "no room to store incoming packets"  (as far i remember the message correctly, sadly, didn't save the log from ffplay) in ffplay. It happens due to a sudden bandwidth spike on the listener side. Not directly related to this crate, just an encoder doing its thing with unlimited bitrate and it loves to push the bandwidth boundaries :). 

I'll fire this up on the remote server and will give a feedback. Thank you a lot!

**Comment by robertream** [comment]
@russelltg do you want to take a look at this or can I merge it?

**Comment by russelltg** [comment]
Go for it. Glad to see Listener fully in

**Pull request merged**
