### PR TITLE
clock sync + congestion control

### PR DESCRIPTION
**Pull request by robertream**
I've only implemented the Live Congestion Control algorithm. I derived it from the reference implementation. I question ever supporting File, it is not a compelling use case for SRT.

### CODE REVIEW

**Comment by russelltg** [comment]
Ugh--I see this supersedes the other PR?

You should have closed the other one. Can we merge that one first, or are there time changes here that aren't in the other one.

**Comment by robertream** [comment]
The changes I made in the second PR were additive. I can close this one if
you’d like?

**Comment by robertream** [comment]
Ok, I say merge the first PR, I've added the few changes you requested to this PR, all except the test module name change. I think that requires further coding standards discussion, test names don't break functionality, so I'd rather get the new functionality integrated now and refactor tests and modules later to comply with an explicit coding standard.

**Comment by russelltg** [comment]
Could you rebase?

**Comment by russelltg** [comment]
Fixes #5

**Pull request closed without merging**
